apiVersion: v1
kind: Service 
metadata:
  name: short-app-port
spec:
  type: NodePort
  ports:
    - port: 3000 # порт внутри кластера, по которому другие поды могут обращаться к указанного пода
      targetPort: 80 # на какой порт пода мы должны стучаться
      nodePort: 31200 # В случае обращения по этому порту 30000-32676 мы должны проксировать его до сервиса
  selector:
    components: front-end # привязываем к поду с label -


