apiVersion: v1
kind: Pod 
metadata:
  name: short-app
  labels:
    components: front-end
spec:
  containers:
    - name: short-app
      image: antonlarichev/short-app
      ports: # проброс портов из контейнера в pod
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"